/* globals JQClass */
/*! Simple JavaScript Inheritance
 * By John Resig http://ejohn.org/
 * MIT Licensed.
 */
// Inspired by base2 and Prototype
!function(){"use strict";var t=!1;window.JQClass=function(){},JQClass.classes={},JQClass.extend=function n(i){var e=this.prototype;t=!0;var o=new this;t=!1;for(var s in i)if("function"==typeof i[s]&&"function"==typeof e[s])o[s]=function(t,n){return function(){var i=this._super;this._super=function(n){return e[t].apply(this,n||[])};var o=n.apply(this,arguments);return this._super=i,o}}(s,i[s]);else if("object"==typeof i[s]&&"object"==typeof e[s]&&"defaultOptions"===s){var r,p=e[s],f=i[s],u={};for(r in p)u[r]=p[r];for(r in f)u[r]=f[r];o[s]=u}else o[s]=i[s];function a(){!t&&this._init&&this._init.apply(this,arguments)}return a.prototype=o,a.prototype.constructor=a,a.extend=n,a}}();
/*! Abstract base class for collection plugins v1.0.2.
	Written by Keith Wood (wood.keith{at}optusnet.com.au) December 2013.
	Licensed under the MIT license (http://keith-wood.name/licence.html). */
!function($){"use strict";function camelCase(t){return t.replace(/-([a-z])/g,function(t,e){return e.toUpperCase()})}JQClass.classes.JQPlugin=JQClass.extend({name:"plugin",defaultOptions:{},regionalOptions:{},deepMerge:!0,_getMarker:function(){return"is-"+this.name},_init:function(){$.extend(this.defaultOptions,this.regionalOptions&&this.regionalOptions[""]||{});var t=camelCase(this.name);$[t]=this,$.fn[t]=function(e){var a=Array.prototype.slice.call(arguments,1),n=this,s=this;return this.each(function(){if("string"==typeof e){if("_"===e[0]||!$[t][e])throw"Unknown method: "+e;var i=$[t][e].apply($[t],[this].concat(a));if(i!==n&&void 0!==i)return s=i,!1}else $[t]._attach(this,e)}),s}},setDefaults:function(t){$.extend(this.defaultOptions,t||{})},_attach:function(t,e){if(!(t=$(t)).hasClass(this._getMarker())){t.addClass(this._getMarker()),e=$.extend(this.deepMerge,{},this.defaultOptions,this._getMetadata(t),e||{});var a=$.extend({name:this.name,elem:t,options:e},this._instSettings(t,e));t.data(this.name,a),this._postAttach(t,a),this.option(t,e)}},_instSettings:function(t,e){return{}},_postAttach:function(t,e){},_getMetadata:function(elem){try{var data=elem.data(this.name.toLowerCase())||"";data=data.replace(/(\\?)'/g,function(t,e){return e?"'":'"'}).replace(/([a-zA-Z0-9]+):/g,function(t,e,a){var n=data.substring(0,a).match(/"/g);return n&&n.length%2!=0?e+":":'"'+e+'":'}).replace(/\\:/g,":"),data=$.parseJSON("{"+data+"}");for(var key in data)if(data.hasOwnProperty(key)){var value=data[key];"string"==typeof value&&value.match(/^new Date\(([-0-9,\s]*)\)$/)&&(data[key]=eval(value))}return data}catch(t){return{}}},_getInst:function(t){return $(t).data(this.name)||{}},option:function(t,e,a){var n=(t=$(t)).data(this.name),s=e||{};if(!e||"string"==typeof e&&void 0===a)return(s=(n||{}).options)&&e?s[e]:s;t.hasClass(this._getMarker())&&("string"==typeof e&&((s={})[e]=a),this._optionsChanged(t,n,s),$.extend(n.options,s))},_optionsChanged:function(t,e,a){},destroy:function(t){(t=$(t)).hasClass(this._getMarker())&&(this._preDestroy(t,this._getInst(t)),t.removeData(this.name).removeClass(this._getMarker()))},_preDestroy:function(t,e){}}),$.JQPlugin={createPlugin:function(t,e){"object"==typeof t&&(e=t,t="JQPlugin"),t=camelCase(t);var a=camelCase(e.name);JQClass.classes[a]=JQClass.classes[t].extend(e),new JQClass.classes[a]}}}(jQuery);