<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Rize\\UriTemplate' => array($vendorDir . '/rize/uri-template/src'),
    'Neutron' => array($vendorDir . '/neutron/temporary-filesystem/src'),
    'Michelf' => array($vendorDir . '/michelf/php-smartypants'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'FFMpeg' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
    'Alchemy' => array($vendorDir . '/alchemy/binary-driver/src'),
);
